name: securefiledrop

services:
  postgres:
    image: postgres:16
    container_name: sfd_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sfd_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    container_name: sfd_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - sfd_minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "mc alias set sfd http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} >/dev/null 2>&1 && mc ready sfd >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sfd_backend
    environment:
      SFD_BUCKET: ${SFD_BUCKET}
      SFD_S3_ENDPOINT: http://minio:9000
      SFD_S3_ACCESS_KEY: minioadmin
      SFD_S3_SECRET_KEY: CHANGE_THIS_LATER
      SFD_MAX_UPLOAD_BYTES: ${SFD_MAX_UPLOAD_BYTES}
      SFD_DOWNLOAD_SECRET: ${SFD_DOWNLOAD_SECRET}
      SFD_ADDR: ":8080"
      SFD_VERSION: "dev"
      SFD_COMMIT: "local"
      SFD_ADMIN_USER: ${SFD_ADMIN_USER}
      SFD_ADMIN_PASS: ${SFD_ADMIN_PASS}
      SFD_SESSION_SECRET: ${SFD_SESSION_SECRET}
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sfd_pgdata:
  sfd_minio_data:
